name: 'Install'

runs:
  using: 'composite'
  steps:
    - name: 'Setup Node'
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: 'Cache node_modules'
      uses: actions/cache@v4
      id: cache-node_modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: 'Install node_modules'
      if: steps.cache-node_modules.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
