name: 'Build'

on:
  workflow_call:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Install'
        uses: ./.github/actions/install
      - name: 'Build'
        run: npm run build:ci
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./dist/
